actor_tensordict:
  _target_: torchrl.modules.TensorDictModule
  _partial_: True
  out_keys: ${model.param_out_keys}

actor:
  _target_: torchrl.modules.ProbabilisticActor
  _partial_: True
  dist_param_keys: ${model.param_out_keys}
  default_interaction_mode: "random"
  policy_distribution_class: OneHotCategorical
  return_log_prob: True

critic:
  _target_: torchrl.modules.ValueOperator
  _partial_: True

# utils
param_out_keys: ["logit"]
out_features_multiplier: 1
