# Task and env
env:
  env_name: HalfCheetah-v3
  env_task: ""
  env_library: gym
  record_video: 0
  n_samples_stats: 1000
  frame_skip: 1
  num_envs: 1
  reward_scaling: 1.0
  noop: 1
  seed: 0

# logger
logger:
  backend: wandb
  exp_name: iql_halfcheetah-medium-v2
  evaluation_interval: 500
  eval_steps: 1000

# Buffer
replay_buffer:
  dataset: halfcheetah-medium-v2
  batch_size: 256

# Optimization
optim:
  device: cuda:0
  lr: 3e-4
  weight_decay: 0.0
  batch_size: 256
  gradient_steps: 100000


# Policy and model
model:
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1

# loss
loss: 
  loss_function: smooth_l1
  gamma: 0.99
  tau: 0.005
  # IQL hyperparameter
  temperature: 3.0
  expectile: 0.7
