# Task and env
env:
  env_name: Hopper-v3
  env_task: ""
  env_library: gym
  record_video: 0
  n_samples_stats: 1000
  frame_skip: 1
  from_pixels: False
  num_envs: 1
  reward_scaling:
  noop: 1
  seed: 0
  evaluation_interval: 1000

# Eval
recorder:
  video: False
  interval: 10000 # record interval in frames
  frames: 10000

# logger
logger:
  backend: wandb
  exp_name: iql_hopper-medium-v2

# Buffer
replay_buffer:
  dataset: hopper-medium-v2
  batch_size: 256

# Optimization
optim:
  device: cpu
  lr: 3e-4
  weight_decay: 0.0
  batch_size: 256
  lr_scheduler: ""
  gradient_steps: 1000000


# Policy and model
model:
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1

# loss
loss: 
  loss_function: smooth_l1
  gamma: 0.99
  tau: 0.05
  # IQL hyperparameter
  temperature: 3.0
  expectile: 0.7
