in_keys: ["observation_vector"]
in_keys_qvalue: ["action", "observation_vector"]
in_keys_policy_module: ["observation_vector"]

activation: elu
num_cells: [400, 300]

policy_network:
  _target_: torchr.modules.partial_tensordictmodule
  _partial_: True  # we still need the out_keys
  module:
    _target_: torchrl.modules.MLP
    _partial_: True
    activation: ${network.activation}
    num_cells: ${network.num_cells}

qvalue_network:
  _target_: torchrl.modules.ValueOperator
  in_keys: ${network.in_keys_qvalue}
  module:
    _target_: torchrl.modules.MLP
    out_features: 1
    activation: ${network.activation}
    num_cells: ${network.num_cells}

value_network:
  _target_: torchrl.modules.ValueOperator
  in_keys: ${network.in_keys}
  module:
    _target_: torchrl.modules.MLP
    out_features: 1
    activation: ${network.activation}
    num_cells: ${network.num_cells}
