in_keys: ["observation_vector"]
in_keys_policy_module: ["observation_vector"]

policy_network:
  _target_: torchrl.modules.MLP
  _partial_: True
  num_cells: [400, 300]

actor_critic:
  _target_: torchrl.modules.ActorCriticWrapper
  _partial_: True
  value_operator:
    _target_: torchrl.modules.ValueOperator
    module:
      _target_: torchrl.modules.MLP
      num_cells: [ 400, 300 ]
      out_features: 1
    in_keys: ${network.in_keys}
