in_keys: ["observation_vector"]
in_keys_policy_module: ["hidden"]
latent_size: 300

policy_network:
  _target_: torchrl.modules.MLP
  _partial_: True
  num_cells: [400, 300]

actor_critic:
  _target_: torchrl.modules.ActorValueOperator
  _partial_: True
  common_operator:
    _target_: torchrl.modules.TensorDictModule
    in_keys: ${network.in_keys}
    out_keys: ["hidden"]
    module:
      _target_: torchrl.modules.MLP
      out_features: ${network.latent_size}
      num_cells: [400]
  value_operator:
    _target_: torchrl.modules.ValueOperator
    module:
      _target_: torchrl.modules.MLP
      out_features: 1
      num_cells: [128, 128]
    in_keys: ["hidden"]
