# Environment
env:
  name: HalfCheetah-v3
  task: ""
  exp_name: "HalfCheetah-TD3-ICLR"
  library: gym
  frame_skip: 1
  seed: 42

# Collection
collector:
  total_frames: 3000000
  init_random_frames: 10000
  init_env_steps: 1000
  frames_per_batch: 1000
  max_frames_per_traj: 1000
  async_collection: 1
  collector_device: cpu
  env_per_collector: 1
  num_workers: 1

# Replay Buffer
replay_buffer:
  prb: 0 # use prioritized experience replay
  size: 1000000

# Optimization
optimization:
  utd_ratio: 1.0
  gamma: 0.99
  loss_function: l2
  lr: 3.0e-4
  weight_decay: 0.0
  batch_size: 256
  target_update_polyak: 0.995
  policy_update_delay: 2
  policy_noise: 0.2
  noise_clip: 0.5

# Network
network:
  hidden_sizes: [256, 256]
  activation: relu
  device: "cuda:0"

# Logging
logger:
  backend: wandb
  mode: online
  eval_iter: 25000
