# environment and task
env:
  name: HalfCheetah-v3
  task: ""
  exp_name: "HalfCheetah-SAC"
  library: gym
  frame_skip: 1
  seed: 1

# collector
collector:
  total_frames: 3_000_000
  init_random_frames: 25000
  frames_per_batch: 1000
  max_frames_per_traj: 1000
  init_env_steps: 1000
  async_collection: 1
  collector_device: cpu
  env_per_collector: 1
  num_workers: 1

# replay buffer
replay_buffer:
  size: 1000000
  prb: 0 # use prioritized experience replay

# optim
optim:
  utd_ratio: 1.0
  gamma: 0.99
  loss_function: l2
  lr: 3e-4
  weight_decay: 0.0
  batch_size: 256
  target_update_polyak: 0.995
  alpha_init: 0.2

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1
  device: "cuda:0"

# logging
logger:
  backend: wandb
  mode: online
  eval_iter: 25000
